#pragma once
#include "NativeGameplayTags.h"

namespace FASGameplayTags
{
	// Abilities
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee);

	// Weapon state
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_IsFiring);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_None);

	// Weapon type
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Pistol);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Rifle);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_RocketLauncher);

	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// Gameplay events that drive the death/respawn ability
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Respawn);
}
