#pragma once

DECLARE_LOG_CATEGORY_EXTERN(LogAS, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAS_Ability, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAS_Input, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAS_Weapon, Log, All);
